### ISSUE TITLE
[Fix] Menu delay problem

### ISSUE THREAD

**Issue by jailanihar** [hafiz10k/UpClose#1]
# Menu delay problem
## The problem
![myimage](https://user-images.githubusercontent.com/16147064/45464343-c70c5980-b742-11e8-88ec-df7ead1becb1.gif)

I clicked the down button every half a second. There is a delay to the movement of the menu selection.

### Menu.java
```java
public void update(Game game) {
		
	.
        .

        // This part is the one that causing the problem.
	Thread.sleep(150);
		
        .
        .
		
}
```

### Description of why it is causing the problem.
The reason why the delay happened is because the update method will constantly be run multiple times while the Menu is rendered. So the `Thread.sleep(150);` is also run multiple times which may cause the unnecessary delay.

## Fix
What you can do is to make sure that `Thread.sleep(150);` will only be run when the user move the menu. I noticed you have implemented `boolean didMove = false` already and set `didMove = true` once the user move the menu. So we can utilise this and do an if statement.
```java
public void update(Game game) {
		
	.
        .

        if(didMove) {
	        Thread.sleep(150);
        }
		
        .
        .
		
}
```
It will only run the delay if the user move the menu.

**Comment by HernieAW9** [comment]
Noted and thank you sir, the solution is already applied to the code.
